import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import RaceCard from "../components/RaceCard";
import { Box, Container, Grid } from "@chakra-ui/react";
import { extendTheme } from "@chakra-ui/react";
const breakpoints = {
  x2l: "10em",
};

// 3. Extend the theme
const theme = extendTheme({ breakpoints });

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>F1 Graphs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW={"5xl"}>
        <Grid h="xl" gap={3} templateColumns={{ base: "repeat(1,1fr)", lg: "repeat(5,1fr)" }}>
          <RaceCard colSpan={3} rowSpan={1} />
          <RaceCard rowSpan={1} />
          <RaceCard rowSpan={1} />
        </Grid>
      </Container>
    </div>
  );
}
